config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}#override default controller to use registrations controller created by Devise
  resources :tweets
  root to: "tweets#index"
end

# devise_for :users is added when you run -- `rails g devise User(model)`

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
    # Parameters needed for sign up
    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_conformation)
    end
    # params for acct update -- current_password(to ensure you enter ur pw during update)
    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_conformation, :current_password)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]#only index & show page do not req authentication

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all.order("created_at DESC")
    @tweet = Tweet.new
   
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    # @tweet = Tweet.new
    @tweet = current_user.tweets.build #(configure controller to work wt Devise)
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    # @tweet = Tweet.new(tweet_params)
    @tweet = current_user.tweets.build(tweet_params)#Only current signed in user should create tweets

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>twitter clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/18a281af1f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container mb-0">
      <% if flash[:notice] %>
        <div class="alert alert-info">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
    <!--<div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>-->
    <%# Navbar %>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      <%= link_to root_path do %>
        <a class="navbar-brand text-white" href="#">Twitter</a>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <%= link_to root_path do %>
            <li class="nav-item active text-white">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
          <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <%= link_to 'New Tweet', new_tweet_path, class: 'btn btn-light my-2 my-sm-0 text-info'%>
        </form>
        <ul class="navbar-nav">
          <li class="nav-item">
            <% if user_signed_in? %>
              <a> <%= link_to "Signed in as " + current_user.name, edit_user_registration_path, class: 'ml-3 text-warning' %></a>
              <a> <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'ml-3 text-white' %></a>
            <% else %>
              <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: 'text-white ml-3' %></li>
              <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: 'text-white ml-3' %></li>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %></div>
  </body>
</html>

app/views/tweets/_feed.html.erb
<% if user_signed_in? %>
  <div class="media">
    <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
    <div class="media-body">
      <%= render "tweets/form" %>
    </div>
  </div>
<% end %>
<div class="col-md-3"><% @tweets.each do |tweet| %>
    <div class="media">
      <%= gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name) %>
      <div class="media-body">
        <p><strong><%= tweet.user.name %></strong></p>
        <p><strong><%= tweet.user.username %></strong></p>
        <p><%= tweet.tweet %></p>
        <% if user_signed_in? %>
          <nav class="nav justify-content-center">
            <%= link_to tweet do %>
              <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to edit_tweet_path(tweet) do %>
              <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to tweet, method: :delete, data: { confirm: 'Are you sure you want to delete tweet?' } do %>
              <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></i></span>
          <% end %>
        </nav>
      <% end %>
    </div>
  </div>
<% end %>
</div>
<!--</div>
<div>
<h1>Tweets</h1>
<table>
  <thead>
    <tr>
      <th>Tweet</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.tweet %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Tweet', new_tweet_path %>
</div>-->

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
  <%= f.error_notification %>
  <div class="form-group">
    <%= f.input :tweet, label: "Tweet about it", input_html: {class: "form-control textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweet" %>
  </div>
  <%= f.button :submit, class: "btn btn-info"%>
<% end %>

app/views/tweets/_profile.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-header">
    Profile
  </div>
  <div><%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %></div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><Strong><%= current_user.name%></Strong></li>
    <li class="list-group-item"><small><%= "@" + current_user.username%></small></li>
  </ul>
  <div class="card-footer">
    <span class="card-header">
      <h2>Tweets</h2>
      <p><Strong><%= current_user.tweets.count %></Strong></p>
    </span>
    <span>
      <h2>Following</h2>
      <p>145</p>
    </span>
    <span class="card-footer">
      <h2>Followers</h2>
      <p>176K</p>
    </span>
  </div>
</div>

app/views/tweets/_trends.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-header">
    Trending
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Cras justo odio</li>
    <li class="list-group-item">Dapibus ac facilisis in</li>
    <li class="list-group-item">Vestibulum at eros</li>
  </ul>
</div>

app/views/tweets/_who-to-follow.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-header">
    Who to follow
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">John doe</li>
    <li class="list-group-item">@John</li>
  </ul>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">John doe</li>
    <li class="list-group-item">@John</li>
  </ul>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <% if user_signed_in? %>
    <div class="col-md-3">
      <%= render 'profile' %>
    </div>
  <% else %>
    <div class="col-md-3">
      <%= render 'trends' %>
    </div>
  <% end %>
  <div class="col-md-5">
    <%= render 'feed' %>
  </div>
  <div class="col-md-4">
    <%= render 'who-to-follow' %>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>